n = input('digite qualquer coisa:')
print('o tipo primitivo é', type(n))
print('só tem espaços?', n.isspace())
print('só tem letra maiúscula?',n.isupper())
print('é um numero?',n.isnumeric())
print('é tudo minusculo?',n.islower())
print('é alfabético?',n.isalpha())
print('ele é alfanumérico?',n.isalnum())
print('ela está captalizada?',n.istitle())