print('INICIO DO PROGRAMA')
nome = str(input('digite seu nome:'))
n = nome.split()
print('muito prazer em te conhecer!')
print('seu primeiro nome é {}'.format(n[0]))
print('seu ultimo nome é {}'.format(n[len(n)-1]))